# Generated by Django 4.0.4 on 2022-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_with_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('application_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('permission', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('auth_token', models.CharField(blank=True, max_length=60, null=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
